### ISSUE TITLE
Crash occurs if docSetId does not have an _

### ISSUE THREAD

**Issue by superdav42** [unfoldingWord/uw-editor#38] opened 2022-11-11 22:59 UTC
Given an id like:
```
  const docSetId = 'unfoldingWord/enult'
```
passing this as a param to <UsfmEditor> causes a crash because epitelete and proskomma are expecting an org, lang and abbr. I think we should make it just work with any string and not have it broken down with / and _ but maybe proskomma can't work that way.

**Comment by mandolyte** [comment] 2022-12-07 14:43
@superdav42 I think you are correct. This is a limitation of pk. A set of documents are grouped by org, lang, and "abbreviation" (1). Then the "docSetId" is created from these. 

PK does have some rules and regex which it used to ensure some consistency with some flexibility. So we may be able to adjust this.

I'll pose the question on discord for us.


(1) "abbreviation" being an abbreviation of the translation name.

**Comment by mandolyte** [comment] 2022-12-07 14:54
Documentation:
https://doc.proskomma.bible/en/dev/graphql_reference/doc_set.html?highlight=regex#selectors

**Comment by mandolyte** [comment] 2022-12-08 11:46
@superdav42 see discussion in discord.
https://discord.com/channels/867746700390563850/872219519584702474/1050064211646087178

**Comment by mvahowe** [comment] 2022-12-08 18:14
@superdav42 @mandolyte I think the only limitation from Proskomma here is what is sometimes called 'typing'. ie don't declare one set of selectors and then expect a different set of selectors to work. Also, it's much much safer to load the document and then read back the docSetId, ratrher than trying to guess it. (You probably wouldn't try to guess a SQL primary key...) I think importDocument() returns something informative.

**Comment by mvahowe** [comment] 2022-12-08 18:17
Also, what crashes? Is there an error message?

**Comment by superdav42** [comment] 2022-12-14 02:13
> Also, what crashes? Is there an error message?

Unhandled Runtime Error
Error: Provided docSetId is not present in the Proskomma instance.

Call Stack
new Epitelete
node_modules/epitelete/dist/index.js (61:0)
new EpiteleteHtml
node_modules/epitelete-html/dist/index.js (28:0)
eval
node_modules/uw-editor/dist/hooks/usePkImport.js (102:0)

To reproduce comment out this line in Gt https://github.com/unfoldingWord/gateway-translate/blob/main/src/context/AppContext.js#L116

Then try to open a book from https://qa.door43.org/unfoldingWord/BHP

**Comment by mvahowe** [comment] 2022-12-26 10:59
@superdav42 Right, so it's not a proskomma issue. At a guess something on Epitelete or EpiteletrHtml is trying to unpick the primary key, which is A Bad Idea, and also unnecessary if you let Proskomma give you the selectors. @abelpz can you reproduce this? Proskomma itself used to use uuids as primary keys (ie no underscores ever).

**Comment by abelpz** [comment] 2022-12-26 11:23
Is this still an issue?

**Comment by abelpz** [comment] 2022-12-26 15:31
Actually that error throws only when the pk query is not successful:
https://github.com/Proskomma/epitelete/blob/9d49a2dafffeabc922317198815e8f1031321d42/src/index.js#L31-L36

Epitelete does not do any shape validation on the docSetId, it uses whatever docSetId provided by the user to make a query using proskomma.gqlQuerySync()

**Comment by birchamp** [comment] 2023-01-09 15:31
@abelpz can you talk to @mvahowe about this?

**Comment by abelpz** [comment] 2023-01-12 13:54
This was discussed on discord, this was Mark's answer: https://discord.com/channels/867746700390563850/872219519584702474/1057005235173867561

I believe Mark's answer before could help with this issue https://github.com/unfoldingWord/uw-editor/issues/38#issuecomment-1343122651

**Comment by mandolyte** [comment] 2023-03-01 12:26
It is my understanding that this situation will not occur in gT now because we have taken care to format the selectors so that the layers get what they expect.

So I'm closing this issue for us.

**Closed by mandolyte** 2023-03-01 12:26 UTC
Labels: bug
